#!/bin/bash -eu

source funcs.t

describe-test "create a shell function named makepath"

testFunctionExists() {
  source ../makepath
  makepath_type=$(type -t makepath)
  assertEquals 'makepath not a function' "$makepath_type"  "function"
}

source shunit2
